# Generated by Django 5.1 on 2024-08-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(verbose_name='Student Grade'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='otp',
            field=models.TextField(max_length=4, null=True, verbose_name='OTP Password'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.TextField(max_length=10, verbose_name='Teacher Phone no.'),
        ),
    ]
