# Generated by Django 5.1 on 2024-08-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_student_grade_alter_teacher_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='displayImage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Student Display Image'),
        ),
    ]
