# Generated by Django 5.1 on 2024-08-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_teacher_onboarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='displayImage',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/StudentDisplayImages', verbose_name='Student Display Image'),
        ),
    ]
