# Generated by Django 5.1 on 2024-08-08 16:49

import django.db.models.deletion
import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_student_displayimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='displayImage',
            field=models.ImageField(blank=True, null=True, upload_to=teacher.models.displayImageFilePath, verbose_name='Student Display Image'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
