# Generated by Django 5.1 on 2024-08-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_student_displayimage_alter_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='otpVerified',
            field=models.BooleanField(default=False, verbose_name='OTP has been verified'),
        ),
    ]
