# Generated by Django 5.0.6 on 2024-08-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_remove_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentDesc',
        ),
    ]
